#!yaml
name: build
on:
  push:
    branches:
      - deploy
  workflow_dispatch:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install php dependencies
        uses: php-actions/composer@v6
        with:
          working_dir: "source/wp-content/themes/mytheme"

      - name: Install node dependencies
        run: npm ci

      - name: Build
        run: npm run build

      # https://github.com/s0/git-publish-subdir-action
      - name: Push to build branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: source/wp-content/themes/mytheme
          TARGET_DIR: mytheme
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
